apps:
- Void
- GVerb
- BCSR
- SpaceFX
- SimpleVCA
- MoogFilt
- PNoise
- FVerb
- CStrip
- StrampDly
- GDVerb2
- MSxxNoise
- CStripM
- EChorus
- APCpp
- FBDlyLine
- WTOsc
- TBD03
- TDelay
- MIDifu
- SineSrc
- MIVerb
- MIVerb2
- MIEnsemble
- SubSynth
- BBeats
- Hihat1
- Rompler
- GDVerb
- Claude
- TBDaits
- TBDeep
- TBDings
- EveryTrim
- Bjorklund
- MIPShft
- Retroactor
- MIChorus
- MISVF
- Dust
- MacOsc
- Subbotnik
- CDelay
- Talkbox
- DLoop
- Formantor
- PolyPad
- VctrSnt
- Karpuskl
- Antique
theme: jekyll-theme-minimal
