apps:
- Void
- GVerb
- BCSR
- SpaceFX
- SimpleVCA
- MoogFilt
- PNoise
- FVerb
- CStrip
- StrampDly
- GDVerb2
- MIEnsemble
- SubSynth
- BBeats
- Hihat1
- Rompler
- GDVerb
- Claude
- TBDaits
- TBDeep
- TBDings
- EveryTrim
- Bjorklund
- MIPShft
- Retroactor
- MIChorus
- MISVF
- Dust
- MacOsc
- CDelay
- DLoop
- Formantor
- PolyPad
- Karpuskl
- Antique
theme: jekyll-theme-minimal
