apps:
- BBeats
- Formantor
- CStrip
- PolyPad
- EChorus
- Void
- MSxxNoise
- MIChorus
- Hihat1
- FBDlyLine
- CStripM
- MISVF
- TBD03
- SpaceFX
- SimpleVCA
- MIVerb
- Antique
- GDVerb2
- TBDeep
- TDelay
- TBDaits
- TBDings
- MoogFilt
- SubSynth
- Bjorklund
- Retroactor
- MIVerb2
- GDVerb
- EveryTrim
- VctrSnt
- StrampDly
- GVerb
- Rompler
- PNoise
- CDelay
- WTOsc
- MacOsc
- APCpp
- SineSrc
- Karpuskl
- DLoop
- MIDifu
- Subbotnik
- Dust
- MIEnsemble
- FVerb
- BCSR
- Talkbox
- Claude
- MIPShft
theme: jekyll-theme-minimal
