apps:
- APCpp
- Antique
- BBeats
- BCSR
- Bjorklund
- CDelay
- CStrip
- CStripM
- Claude
- DLoop
- Dust
- EChorus
- EveryTrim
- FBDlyLine
- FVerb
- Formantor
- Freakwaves
- GDVerb
- GDVerb2
- GVerb
- Hihat1
- Karpuskl
- MIChorus
- MIDifu
- MIEnsemble
- MIPShft
- MISVF
- MIVerb
- MIVerb2
- MSxxNoise
- MacOsc
- MoogFilt
- PNoise
- PolyPad
- RecNPlay
- Retroactor
- Rompler
- SimpleVCA
- SineSrc
- SpaceFX
- StrampDly
- SubSynth
- Subbotnik
- TBD03
- TBDaits
- TBDeep
- TBDings
- TDelay
- Talkbox
- VctrSnt
- Void
- WTOsc
theme: jekyll-theme-minimal
