# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the gh-pages branch
  push:
    branches: [ gh-pages ]
  pull_request:
    branches: [ gh-pages ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout tbd-cloud-compiler repository
        uses: actions/checkout@v2
        
      - name: Checkout ctag-tbd repository
        uses: actions/checkout@v2
        with:
          repository: 'https://github.com/ctag-fh-kiel/ctag-tbd'
          path: 'ctag-tbd'

      # List workspace
      - name: Run a one-line script
        run: ls -al

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          cd ctag-tbd
          ls -al
